services:
  - type: web
    name: labezra-pos
    env: python
    region: oregon
    plan: free

    buildCommand: >
      pip install --upgrade pip setuptools wheel &&
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate --noinput

    startCommand: >
      gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120

    envVars:
      - key: DEBUG
        value: "false"

      - key: DJANGO_SECRET_KEY
        generateValue: true

      - key: ALLOWED_HOSTS
        value: "labezra-pos.onrender.com"

      - key: CSRF_TRUSTED_ORIGINS
        value: "https://labezra-pos.onrender.com"

      - key: PYTHON_VERSION
        value: "3.11.0"