# Generated by Django 5.0 on 2026-03-22 19:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='company.company')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['company'], name='expenses_ex_company_afc5d3_idx'), models.Index(fields=['date'], name='expenses_ex_date_17a2b2_idx')],
            },
        ),
    ]
