# Generated by Django 5.0 on 2026-03-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='next_invoice_number',
            field=models.IntegerField(default=1),
        ),
    ]
