# Generated by Django 5.0 on 2026-03-15 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessinvoice',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='businessinvoice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessinvoice',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='businessinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='businessinvoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='businessinvoice',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='businessinvoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.businessinvoice'),
        ),
        migrations.AlterField(
            model_name='businessinvoiceitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='businessinvoiceitem',
            name='qty',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
    ]
